:shirt:

diff --git a/script/asset-build b/script/asset-build
--- a/script/asset-build
+++ b/script/asset-build
@@ -1,6 +1,20 @@
 #!/usr/bin/env bash
 
-cd $phoenix_dir
+set -e
+
+ # shellcheck disable=SC2154
+if [ -n "$phoenix_dir" ]; then
+  echo "Error: phoenix_dir variable is not assigned"
+  exit 1
+fi
+
+# shellcheck disable=SC2154
+if [ -n "$phoenix_ex" ]; then
+  echo "Error: phoenix_ex variable is not assigned"
+  exit 1
+fi
+
+cd "$phoenix_dir" || exit 1
 
 npm --prefix ./assets run deploy
 
